export const USERS_FETCH = 'USERS_FETCH';
export const USERS_FETCH_OK = 'USERS_FETCH_OK';
export const USERS_FETCH_NG = 'USERS_FETCH_NG';

export const USER_FETCH = 'USER_FETCH';
export const USER_FETCH_OK = 'USER_FETCH_OK';
export const USER_FETCH_NG = 'USER_FETCH_NG';

// Jira
export const JIRA_GET_ISSUES = 'JIRA_GET_ISSUES';
export const JIRA_GET_ISSUES_OK = 'JIRA_GET_ISSUES_OK';
export const JIRA_GET_ISSUES_NG = 'JIRA_GET_ISSUES_NG';

export const JIRA_FIND_USERS_ASSIGNABLE = 'JIRA_FIND_USERS_ASSIGNABLE';
export const JIRA_FIND_USERS_ASSIGNABLE_OK = 'JIRA_FIND_USERS_ASSIGNABLE_OK';
export const JIRA_FIND_USERS_ASSIGNABLE_NG = 'JIRA_FIND_USERS_ASSIGNABLE_NG';

export const JIRA_GET_ALL_PROJECT = 'JIRA_GET_ALL_PROJECT';
export const JIRA_GET_ALL_PROJECT_OK = 'JIRA_GET_ALL_PROJECT_OK';
export const JIRA_GET_ALL_PROJECT_NG = 'JIRA_GET_ALL_PROJECT_NG';

